"""Changed user database

Revision ID: 44109df49a1f
Revises: 0e275921bc33
Create Date: 2022-03-10 09:57:51.373228

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '44109df49a1f'
down_revision = '0e275921bc33'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'profile_image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('profile_image', mysql.VARCHAR(length=200), nullable=True))
    # ### end Alembic commands ###
