"""Updated posts

Revision ID: 7ff8a30a249c
Revises: fbb221e137f0
Create Date: 2022-03-01 11:22:36.982693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ff8a30a249c'
down_revision = 'fbb221e137f0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('extra_col', sa.String(length=255), nullable=True))
    op.add_column('posts', sa.Column('date_posted', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'date_posted')
    op.drop_column('posts', 'extra_col')
    # ### end Alembic commands ###
