"""Updated posts

Revision ID: 8fa4fb453b38
Revises: 7ff8a30a249c
Create Date: 2022-03-01 11:23:11.475953

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8fa4fb453b38'
down_revision = '7ff8a30a249c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('author', sa.String(length=255), nullable=True))
    op.drop_column('posts', 'extra_col')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('extra_col', mysql.VARCHAR(length=255), nullable=True))
    op.drop_column('posts', 'author')
    # ### end Alembic commands ###
