"""Added foreign key

Revision ID: 8fa4e8d8505c
Revises: 2ca1d2ec9329
Create Date: 2022-03-04 09:51:57.868786

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8fa4e8d8505c'
down_revision = '2ca1d2ec9329'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('poster_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'posts', 'user', ['poster_id'], ['id'])
    op.drop_column('posts', 'author')
    op.drop_column('user', 'fav_color')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('fav_color', mysql.VARCHAR(length=200), nullable=True))
    op.add_column('posts', sa.Column('author', mysql.VARCHAR(length=255), nullable=True))
    op.drop_constraint(None, 'posts', type_='foreignkey')
    op.drop_column('posts', 'poster_id')
    # ### end Alembic commands ###
