"""Added some more fields in user and updated profile layout in the user dashboard

Revision ID: c15a974efb8f
Revises: e26e2be62f87
Create Date: 2022-03-05 16:21:36.340791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c15a974efb8f'
down_revision = 'e26e2be62f87'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('experience', sa.String(length=3), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'experience')
    # ### end Alembic commands ###
