"""Updated posts

Revision ID: fbb221e137f0
Revises: ba1dba87a13b
Create Date: 2022-03-01 11:21:44.325161

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fbb221e137f0'
down_revision = 'ba1dba87a13b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('posts', 'date_posted')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('date_posted', mysql.DATETIME(), nullable=True))
    # ### end Alembic commands ###
